language: common-lisp

env:
  matrix:
    - LISP=abcl
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl
    - LISP=sbcl
    - LISP=sbcl32

matrix:
  allow_failures:
    - env: LISP=cmucl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  - cl -e "(cl:in-package :cl-user)
           (dolist (p '(:asdf :fiveam))
             (ql:quickload p :verbose t))"

script:
  - cl -e '(cl:in-package :cl-user)
           (ql:quickload :cl-reverse-read-file-test)
           (setf fiveam:*debug-on-error* t)
           (setf fiveam:*debug-on-failure* t)
           (setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))
           (asdf:test-system :cl-reverse-read-file-test)'
